change to gpu support
JDACS4C-IMPROVE/Singularity pull request #111
Opened 2024-02-25 08:39 UTC by RylieWeaver

2024-02-25 20:06 UTC, wilke requested changes
Looks good. Could you change the directories for candle_lib, improve and uno? Place everything under /usr/local

Don't use SINGULARITY_ROOTFS, this is only available at build time.

2024-02-25 20:06 UTC, wilke commented on definitions/Uno_Improve.def
>          PATH=$PATH:$SINGULARITY_ROOTFS/IMPROVE/${MODEL}
Not SINGULARITY_ROOTFS, the model is checked out in /usr/local/

2024-02-25 20:06 UTC, wilke commented on definitions/Uno_Improve.def
> +        export PYTHONPATH=/opt/IMPROVE/:/opt/candle_lib/:$PYTHONPATH
Change to /usr/local/candle_lib. What is in /opt/IMPROVE?

2024-02-25 20:06 UTC, wilke commented on definitions/Uno_Improve.def
>      git clone -b develop https://github.com/JDACS4C-IMPROVE/IMPROVE.git /opt/IMPROVE
remove /opt/IMPROVE, you are using /usr/local as your target directory for install

2024-02-25 20:06 UTC, wilke commented on definitions/Uno_Improve.def
> +    git clone -b develop https://github.com/ECP-CANDLE/candle_lib.git /opt/candle_lib
same here, install candle_lib under /usr/local, don't forget to update PYTHONPATH. I assume you are not using the pip version because of some dependency conflicts?

2024-02-25 20:06 UTC, wilke commented on definitions/Uno_Improve.def
>          PATH=$PATH:$SINGULARITY_ROOTFS/IMPROVE/${MODEL}
Set IMPROVE_MODEL_DIR  to the directory containing the python scripts for preprocessing, training and inference, something like IMPROVE_MODEL_DIR=/usr/local/Benchmarks/...../uno_improve/

2024-02-25 20:07 UTC, wilke commented on definitions/Uno_Improve.def
>          PATH=$PATH:$SINGULARITY_ROOTFS/IMPROVE/${MODEL}
Appreciate your help. It looks good otherwise, and I will rebuild after the changes.

2024-02-26 09:55 UTC, RylieWeaver commented on definitions/Uno_Improve.def
> +        export PYTHONPATH=/opt/IMPROVE/:/opt/candle_lib/:$PYTHONPATH
Some combination of seeing it in another def file and hearing on stack overflow that it's a common place to put cloned repos, smh.

Will change.

2024-02-26 09:55 UTC, RylieWeaver commented on definitions/Uno_Improve.def
>          PATH=$PATH:$SINGULARITY_ROOTFS/IMPROVE/${MODEL}
Thanks for the feedback. Let me know if the latest commit is what you're looking for. This should be putting everything in /usr/local and not using SINGULARITY_ROOTFS in ways it's not suited for

2024-02-26 18:48 UTC, wilke approved these changes
LGTM

2024-02-26 18:53 UTC, merged