o Add SWnet def file
JDACS4C-IMPROVE/Singularity pull request #74
Opened 2023-09-26 20:23 UTC by rajeeja

Please test

2023-09-26 20:40 UTC, wilke requested changes
Please add 

%environment
    export IMPROVE_MODEL_DIR=/usr/local/{{MODEL}}


This will be used in train.sh, see https://github.com/JDACS4C-IMPROVE/Singularity/blob/develop/src/templates/train.sh

2023-09-29 16:24 UTC, rajeeja commented
#6 this might fix it.

2023-09-29 16:41 UTC, wilke reviewed
Apart from the environment section which is not functional, I don't see a difference to the version in the switch-to-improve branch.

2023-09-29 16:41 UTC, wilke commented on definitions/SWnet.def
> +	export IMPROVE_MODEL_DIR=/usr/local/{{MODEL}}
This is a template. Replace {{MODEL}} with name of the model dir.

2023-09-29 16:42 UTC, closed without merging